### ISSUE TITLE
Dropin - Unsupported argument

### ISSUE THREAD

**Issue by ghost** [rochacon/bastrd#1]
Code:
data "ignition_systemd_unit" "docker_block_ec2_metadata" {
  name = "docker.service"

  dropin = {
    name = "10-block-ec2-metadata.conf"

    content = <<EOF
[Service]
ExecStartPost=/usr/sbin/iptables -I DOCKER-USER -i docker0 -d 169.254.169.254/32 -j REJECT
EOF
  }
}

------------------------------------------------------------------------------------------------------------------
Error:
  on ec2_userdata.tf line 74, in data "ignition_systemd_unit" "docker_block_ec2_metadata":
  74:   dropin = {

An argument named "dropin" is not expected here. Did you mean to define a
block of type "dropin"?

**Comment by ghost** [comment]
When I run terraform plan:

Error: Error refreshing state: 2 errors occurred:
	* data.ignition_config.userdata: 1 error occurred:
	* data.ignition_config.userdata: data.ignition_config.userdata: No valid JSON found, make sure you're using .rendered and not .id: invalid character 'c' looking for beginning of value

**Comment by rochacon** [comment]
@mbaetaoliveira this seems like a problem due to Terraform upgrade. Are you using 0.12.x?

**Comment by ghost** [comment]
Now I am using 0.12.x, but also I've tested with 0.11.14

**Comment by rochacon** [comment]
@mbaetaoliveira I've upgraded the scripts to Terraform v0.12.x and latest plugins versions and was able to provision a new instance.

Could you please please run `terraform init -upgrade` and use PR above to validate the fix?
